language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
script: 'bundle exec rake'
matrix:
  include:
  - rvm: 2.4.0
    before_install:
      - gem uninstall libxml-ruby
      - sudo apt-get install libxml2
      - gem update bundler

notifications:
  email:
    recipients:
      - jatesins@ncsu.edu
    on_failure: change
    on_success: never
